# Generated by Django 2.0.7 on 2018-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
