# Generated by Django 2.0.7 on 2018-07-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age_of_Customer', models.CharField(choices=[('Fill your Age', 'Fill your Age'), ('0-20', '0-20'), ('21-40', '21-40'), ('41-60', '41-60'), ('61+', '61+')], default='Fill your Age', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
