# Generated by Django 2.0.7 on 2018-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='age',
        ),
    ]
