# Generated by Django 2.0.7 on 2018-07-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0003_delete_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
