# Generated by Django 2.0.7 on 2018-07-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0005_auto_20180731_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='Looa',
        ),
    ]
