# Generated by Django 2.0.7 on 2018-07-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0006_auto_20180731_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Looa',
        ),
    ]
