# Generated by Django 2.0.7 on 2018-07-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0011_auto_20180731_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
