# Generated by Django 2.0.7 on 2018-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0013_aug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Aug',
        ),
    ]
