# Generated by Django 2.0.7 on 2018-07-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eexam', '0014_auto_20180731_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
    ]
